version: 0.2

phases:
  install:
    # runtime-versions:
    #   python: 3.8
    commands:
       - echo "Installing dependencies..."
      #  - sudo apt-get update -y
       - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nginx
       - pip install --upgrade pip
       - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running pre-build tests..."
      - python -m unittest discover -s tests || echo "No tests found"

  build:
    commands:
      - echo "Building application..."
      - cp app.py  requirements.txt /var/www/html/
      - cp -r templates static /var/www/html/

  post_build:
    commands:
      - echo Configured NGINX
      # - zip -r flask_app.zip build/

artifacts:
  files:
    - app.py
    - requirements.txt
    - templates/**
    - static/**
    # - scripts/**
  discard-paths: no
